### ISSUE TITLE
How to Create a new User/Project

### ISSUE THREAD

**Issue by Wipsly** [byjml/multitenant-example#1]
Hi, 

i really like this git but I don't know how to create a new User... I tried a few different thinks, but nothing works for me. In my UsersController there is a store function and I collect the fields from my form.

public function store()
    {
        $user = $this->request->all();
    }

But how can i create a new User with these values?

**Comment by byjml** [comment]
Hi 2,

Since the user belongs to a tenant you would usually do something like this:

```
$tenant = Client::findOrFail($id)
                  ->users()
                  ->create($this->request->all());
```

If I wanted to create both the tenant and the user at once (e.g. when new tenant registers), I'd create the tenant first and then the user, like you see below:

```
$tenant = Client::create($this->request->only('subdomain'));
$user = Client::findOrFail($tenant->id)
              ->users()
              ->create($this->request->only('email', 'username', 'password'));
```

**Comment by Wipsly** [comment]
Hi,

thank you for your answer and the work you did so far. 

Now I can create new users and save them. Thank you very much.

My store function looks like this. 
public function store()
    {
        $user = Auth::user()->client->id;
        $tenant = Client::find($user)
                  ->users()
                  ->create($this->request->all());

```
    return redirect('users');
}
```

**Comment by Wipsly** [comment]
Can be closed.

**Comment by Wipsly** [comment]
Example from my ticket controller

$ticket = new Ticket; 
         $ticket->title = $this->request->input('title'); 
         $ticket->content = $this->request->input('content');
         $ticket->user_id = Auth::user()->id; 
         $ticket->client_id = Auth::user()->client->id;

```
     $ticket->save(); 
```
